### ISSUE TITLE
Diagrama d'activitats dels casos d'ús

### ISSUE THREAD

**Issue by carmenred** [Mensaka/GS1#20]

**Comment by carmenred** [comment]
![image](https://user-images.githubusercontent.com/37579990/51836860-ee368280-2301-11e9-9ed0-7e92bb90c1e7.png)

**Comment by carmenred** [comment]
![image](https://user-images.githubusercontent.com/37579990/52116768-4d520b00-2612-11e9-8aab-cad331b3083e.png)

formularis

**Comment by JordiVilamuCasado** [comment]
![image](https://user-images.githubusercontent.com/44288090/52209022-dbccc380-2882-11e9-8552-9a6f28f947c0.png)
Consulta d'usuaris

**Comment by carmenred** [comment]
![image](https://user-images.githubusercontent.com/37579990/52951823-18b8b000-3383-11e9-827b-339ffaf1b34f.png)
